### ISSUE TITLE
我用ESP32 做了个HTML5的网站，用于传出麦克风信息

### ISSUE THREAD

**Issue by lixy123** [2fps/recorder#10]
你好，我用ESP32 做了个HTML5的网站，用于传出麦克风信息.  目前还有BUG, 邀请你一块参与. 这是树莓派做智能音箱的一个扩展项目， 我对网页传声音不太熟悉，看能否帮助指导下 https://github.com/lixy123/ESP32_Remote_MIC

**Comment by 2fps** [comment]
嘿嘿，我也只是略懂略懂。我会抽空看下你的项目。
