### ISSUE TITLE
在此基础上有办法语音转文字吗？

### ISSUE THREAD

**Issue by 734208213** [2fps/recorder#11]

**Comment by 2fps** [comment]
可以将获取到的PCM音频数据发送到平台去识别，如阿里云的可以参考[链接](http://www.zhuyuntao.cn/%E5%9F%BA%E4%BA%8E%E9%98%BF%E9%87%8C%E4%BA%91%E5%AE%9E%E7%8E%B0%E7%AE%80%E5%8D%95%E7%9A%84%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB%E5%8A%9F%E8%83%BD)

**Comment by 734208213** [comment]
谢谢指导^_^
