### ISSUE TITLE
如果能够提供一个模版demo就更好了

### ISSUE THREAD

**Issue by lmxhappy** [2fps/recorder#12]
您的demo页面，无法立即使用，找不到代码。谢谢

**Comment by 2fps** [comment]
你好，我尝试了demo地址可以访问。若无法访问，可以将代码clone到本地，`npm ci`安装依赖后，输入`npm run dev`在本地启动一个demo。

详细的使用你可以参考下README中的API或example文件夹，demo上的代码都位于example文件夹中。
