### ISSUE TITLE
请求在start函数抛出异常的代码部分增加一个promise.reject让调用能够catch住

### ISSUE THREAD

**Issue by csfankun** [2fps/recorder#13]
你好我们项目组在使用
recorder.start().catch(e => )的代码中，在浏览器拒绝音频录音时发现进不到catch函数中，所以请求能够在异常情况时能够在catch函数中调用以提示给用户

**Comment by 2fps** [comment]
error已经被我在内部catch了。。我会增加个reject

**Comment by csfankun** [comment]
你好，涛老师，大概什么时候能够增加个promise.reject的发布版本出来，我一直在等

**Comment by 2fps** [comment]
别喊我老师。。。我也是菜鸡，两问题都改了，麻烦先拿dev分支下的dist目录中的文件，替换node_modules中的进行测试，晚上要细测下再提交版本
