### ISSUE TITLE
在线录制的pcm格式音频如何传递到springboot后端

### ISSUE THREAD

**Issue by Leemenmen** [2fps/recorder#137]
前端使用react
在录音结束后使用formData.append('pcmFile', recorder.getPCMBlob()，'voice.pcm')传递获取到的pcm blob流，后端接收为 (@RequestParam MultipartFile pcmFile) ,但是在后端接收到voice.pcm文件用pcm播放器打开播放只有杂音

**Comment by Leemenmen** [comment]
已解决，是因初始化recorder的时候没有定义参数，定义之后就可以接收到正确的pcm文件了
let recorder = new Recorder({
        sampleBits: 16,                 // 采样位数，支持 8 或 16，默认是16
        sampleRate: 16000,              // 采样率，支持 11025、16000、22050、24000、44100、48000，根据浏览器默认值，我的chrome是48000
        numChannels: 1,                 // 声道，支持 1 或 2， 默认是1
    });

**Comment by funnyqueen** [comment]
你是怎么在本地播放的？
