### ISSUE TITLE
在next.js的seo架构里import 'js-audio-recorder'会报错

### ISSUE THREAD

**Issue by csfankun** [2fps/recorder#14]
你好涛老师：

我在使用next.js对seo架构使用您的模块包发现会报错window，document is not defined，这是基于seo架构一开始渲染时是服务端而非客户端所以没有window对象。

看了下的源码里window是直接调用的，所以请求对window做一个判断处理，判断window对象是否存在。

**Comment by 2fps** [comment]
收到，ssr的还没测试过的，我会尝试测试下

**Comment by 2fps** [comment]
0.4.3已支持了，不过不要在全局或者node会处理的生命周期里使用他。

**Comment by renzhichaos** [comment]
那怎么使用?
