### ISSUE TITLE
onprocess回调返回表示音频文件大小的size

### ISSUE THREAD

**Issue by FrankKai** [2fps/recorder#21]
实时返回Byte类型的size。
可用于实现 **达到设定的size大小，自动停止录制。** 的功能。

**Comment by 2fps** [comment]
不错的建议

**Comment by 2fps** [comment]
不过，由于录音使用的是缓冲器收集数据的，我设置的缓冲是4096个音频（设置太小对性能有影响），就处理，理论上大小是每次按 4096 / (输入采样率/输出采样率) * (输出采样位数 / 8) / 1024个字节增长的，即，48000输入-》16000输出采样，8采样位数的，每次就差1333字节，所以实际还是有偏差的

**Comment by FrankKai** [comment]
可以用什么手段patch掉差的1333字节吗？

现在可以通过** 执行stop方法以后，disconnect以后，再通过getWAVBlob方法获得音频文件**，size属性就是文件最终的大小。

或者是不是可以通过什么操作模拟一下上面的? 比如特地新增一个buffer，一边录制一边实时模拟上面的操作。

**Comment by 2fps** [comment]
不好意思，4096/3算错了。。4096/3越等于1365字节。

我觉得你理解错了。比如你设定到2000字节就stop,但数据实际是以1365个字节增加的，第一次1365字节不满足继续录音，第二次1365*2=2730，此时已经大于2000字节了。感觉让外部去控制大小似乎不太合适。

0.5.2版本中已经有fileSize显示录音大小了。onprocess不推荐使用了，我已经在onprogress回调中增加了fileSize属性获取文件大小，也支持实例下属性fileSize获取大小。比如
```js
recorder.onprogress = function(params) {
    console.log('已录音文件大小（字节）', params.fileSize);
}
// 或者
recorder.fileSize
```
