### ISSUE TITLE
pcm 数据如何压缩

### ISSUE THREAD

**Issue by Liuninggithub** [2fps/recorder#24]
拿到的pcm数据太大 给如何压缩？按照文档最大的压缩比 1s生成的文件也大概30k左右

**Comment by 2fps** [comment]
文档中的压缩，只是针对采样率做压缩（调整）的，实际得到的仍是未压缩的（相对于输出采样率）。前端压缩音频的还不太了解。。。是不是可以借助后端来实现，毕竟后端处理音频的库相对要多、成熟些

**Comment by xiangyuecn** [comment]
理论上pcm ：
`单声道、8位、8000采样率` 一秒大小 `(8/8)*8000/1024` ≈ `8 kb /s` 音质奇差😂
`单声道、16位、16000采样率` 一秒大小 `(16/8)*16000/1024` ≈ `31 kb /s` 音质还行

用 [zhuker/lamejs](https://github.com/zhuker/lamejs) 编码成mp3吧：
`单声道、16kbps、16000采样率` 一秒大小 `16/8` ≈ `2 kb /s` 音质还行
`单声道、68kbps、48000采样率` 一秒大小 `64/8` ≈ `8 kb /s` 其实32kbps以上音质基本完美了

看吧，同样8kb每秒的文件大小，音质是一个天上一个地下😂 不过lamejs对低采样率的pcm进行编码会有bug，需要自己修复一下[参考这篇wiki文档](https://github.com/xiangyuecn/Recorder/wiki/lamejs-bug%E4%BF%AE%E5%A4%8D%E8%AE%B0%E5%BD%95)。

最小的mp3 为`8kbps`的 `8/8 ≈ 1kb/s`，音质太差，还是`16kbps`的`2 kb /s` 综合来看最佳。
