### ISSUE TITLE
safari 重复录音问题需要录音完销毁实例，然后重复录制的时候创建实例

### ISSUE THREAD

**Issue by loveyoubaby5120** [2fps/recorder#25]
safari 重复录音问题需要录音完销毁实例，然后重复录制的时候创建实例

但是销毁后播放、暂停、停止又无法使用
需要在销毁前录音blob存储起来，然后自己去创建audio

**Comment by 2fps** [comment]
重复录音要销毁实例是demo中判断错误了。。。目前已经修改，最新的[demo](https://recorder.zhuyuntao.cn/)已经正常了。

我这边实现的就是只保存当前录音的数据，点击录音开启后，是会将前一次录音数据清空的。因为每次录音都保存的话，会占用较多的内存，保存哪些数据应该交由开发者(插件外)去控制。
