### ISSUE TITLE
 Type 'typeof import("vconsole")' has no construct signatures

### ISSUE THREAD

**Issue by qq459673705** [2fps/recorder#29]
直接运行源码会报错

**Comment by 2fps** [comment]
请提供下操作步骤，谢谢

**Comment by qq459673705** [comment]
没事了，这一部分应该是兼容移动端的，我把那块代码屏蔽了，就行了。
另外 报错信息不影响web端展示。

**Comment by 2fps** [comment]
vconsole是在移动端看打印的，当时用来测兼容性的。话说，报错是怎么来的，`npm run start`后出现的？不影响的话，我也想改下额....
