### ISSUE TITLE
手机端暂停后，不能恢复录音

### ISSUE THREAD

**Issue by yanjun98** [2fps/recorder#32]
非常感谢Issuse30的快速修复。
在手机端还发现暂停后不能恢复录音，桌面没有问题。也没有报错。

**Comment by yanjun98** [comment]
resumeRecord(): void {
        this.audioInput && this.audioInput.connect(this.analyser);
        this.analyser.connect(this.recorder);
        this.recorder.connect(this.context.destination);
        **this.audioInput.connect(this.recorder);**
    }
recorder.ts , 暂停录音 加上下面的这句。

**Comment by 2fps** [comment]
不能恢复？是指恢复录音后，再次播放，暂停恢复后的录音没有播放么？
改了，暂停恢复后的还是不能播放。似乎pc端，safari下也有这个问题

**Comment by 2fps** [comment]
尝试了下，在safari下，disconnect后一小撮时间没有connect上，就会收不到音频数据。

这个问题其他人也遇到了[AudioNode.disconnect() followed by .connect() not working in Safari](https://stackoverflow.com/questions/58564669/audionode-disconnect-followed-by-connect-not-working-in-safari)，还有种就是在`onaudioprocess`种加if判断吧，我先试试吧。

**Comment by yanjun98** [comment]
谢谢，确实是偶发的。 我也再看看。

**Comment by 2fps** [comment]
前面提到的，safari下，暂停后再恢复不能录音的问题改了，版本1.0.3和0.5.6

**Comment by zouzhibin** [comment]
在chrome浏览器上还是出现 点击播放之后不能继续录音 我看https://recorder.zhuyuntao.cn/这个网站就出现了

**Comment by 2fps** [comment]
@zouzhibin 能描述下如何操作的么？我这没有试出来
