### ISSUE TITLE
为什么不支持getWholeData和getNextData了呢？

### ISSUE THREAD

**Issue by julin69** [2fps/recorder#38]
为什么不支持getWholeData和getNextData了呢？如果想要实现类似的效果，应该怎么做？

**Comment by julin69** [comment]
现在我调用getWholeData和getNextData都返回undefined，我们是想要连续的往后端传送数据，不知道应该怎么做？

**Comment by 2fps** [comment]
1.x的整理了下，现将边录边转给删了，如果想使用可以用 0.5.6 版本的。

该功能后面会加上的。

**Comment by julin69** [comment]
您好，非常感谢您的回复！我现在还有一个问题，就是如何把getNextData返回的数组数据转化为PCM数据，传给后端？
