### ISSUE TITLE
如果需要通过websocket往后端传送数据的话，应该怎么操作？

### ISSUE THREAD

**Issue by julin69** [2fps/recorder#39]

**Comment by 2fps** [comment]
实时传可以用0.5.6版本的，录完音后传可以使用`getPCMBlob `获取对应的blob数据。

**Comment by julin69** [comment]
您好，非常感谢您的回复！我现在已经换成了0.5.6的版本，然后我用了如下代码：
self.recoderDataTimer = setInterval(() => {
    var nextData = self.audioRecorder.getNextData();
    console.log("nextData", nextData)
}, 1000)
可是我有点不明白，nextData 取出来的数据怎么是DateView数组啊，这是什么格式的数据？后端拿到这个数组后怎么办才能变成PCM数据？前端能直接给后端传PCM数据吗？

**Comment by 2fps** [comment]
二进制的pcm数据吧，不过是可读可写状态的。你可以将DateView数据转换成blob数据再发送给后端。

后端需要将这些数据有序的拼接起来就是完整pcm数据了。

**Comment by julin69** [comment]
有点不明白，PCM数据怎么是blob格式的，他们两个是什么关系？后端让我传给他PCM数据，我用了getPCMBlob()。可是后端说他接收到的是blob，这是怎么回事？

**Comment by julin69** [comment]
前端怎么将DateView数据转换成blob数据再发送给后端？

**Comment by 2fps** [comment]
Blob对象表示一个不可变、原始数据的类文件对象。这边只是将pcm的数据用blob去表示，blob是前端表示一块二进制数据的格式。至于后端收到的，那是后端需要去处理的了。

new Blob吧，DataView数据应该也是可以发送的。

**Comment by julin69** [comment]
麻烦看下是像这样吗？
var nextData = self.audioRecorder.getNextData();
var nextBlobData = new Blob(nextData);

**Comment by julin69** [comment]
上面的代码var nextBlobData = new Blob(nextData);，此时nextBlobData 里面的数据是PCM吗？

**Comment by 2fps** [comment]
blob参数不对吧，你可以去MDN查下blob用法.
里面是pcm的数据。

**Comment by julin69** [comment]
我查过了，new Blob( array, options );options可以不传，运行后也没有报错。感觉没问题啊。难道说array不能直接用getNextData()返回的数组？

**Comment by 18310035303** [comment]
我切换到0.5.6版本后api不能正常使用，录完音后发现size大小还是0

**Comment by 18310035303** [comment]
兄弟，websocket那个上传录音数据你搞得怎么样了

**Comment by julin69** [comment]
> 兄弟，websocket那个上传录音数据你搞得怎么样了

可以弄，之前是在0.5.6的版本中搞的，流程也通了，但是效果不是太好，断断续续的。

**Comment by 18310035303** [comment]
我这往上传的时候字节流一直是0，能给个demo片段吗？感谢

**Comment by julin69** [comment]
> 我这往上传的时候字节流一直是0，能给个demo片段吗？感谢

需要开启边录边转换的，你开启了吗？compiling  多查下API文档吧。里面写的很清楚了。

**Comment by 18310035303** [comment]
开启了，录完音后也能播放，但是通过websocket去发送这个字节流就是不行

**Comment by julin69** [comment]
> 开启了，录完音后也能播放，但是通过websocket去发送这个字节流就是不行

把你的代码贴出来，要不然没法看

**Comment by 18310035303** [comment]
playV() {
      this.initwebsocket(url);
      if (!this.complete) {
        if (!this.isplay) {
          recorder.start().then(
            () => {
              this.handleText(this.comtext.s[this.num - 1]);
              this.errorshow = !1;
              this.isplay = !0;
            },
            error => {
              Toast("该浏览器暂不支持录音");
            }
          );
          this.timeInt = setInterval(() => {
            var nextData = recorder.getNextData();
            var nextBlobData = new Blob(nextData);
            this.websock.send(nextBlobData);
            console.log("nextBlobData", nextBlobData);
          }, 1000);
        }
      } else {
        Toast("录音完成,训练预计需要20分钟");
      }
    },
    pauseV() {
      if (this.timeInt != null) {
        clearInterval(this.timeInt);
      }
      if (this.isplay) {
        recorder.stop();
        this.isplay = !1;
        // this.upload();
      }
    },

**Comment by julin69** [comment]
> playV() {
> this.initwebsocket(url);
> if (!this.complete) {
> if (!this.isplay) {
> recorder.start().then(
> () => {
> this.handleText(this.comtext.s[this.num - 1]);
> this.errorshow = !1;
> this.isplay = !0;
> },
> error => {
> Toast("该浏览器暂不支持录音");
> }
> );
> this.timeInt = setInterval(() => {
> var nextData = recorder.getNextData();
> var nextBlobData = new Blob(nextData);
> this.websock.send(nextBlobData);
> console.log("nextBlobData", nextBlobData);
> }, 1000);
> }
> } else {
> Toast("录音完成,训练预计需要20分钟");
> }
> },
> pauseV() {
> if (this.timeInt != null) {
> clearInterval(this.timeInt);
> }
> if (this.isplay) {
> recorder.stop();
> this.isplay = !1;
> // this.upload();
> }
> },

前端代码没有问题，后端websocket接收的格式好像不支持blob，后端只支持Bytes。
可以只传给后端nextData试试

**Comment by 18310035303** [comment]
好的，我这边让后端改一下看看，你是直接传的Dataview

**Comment by 18310035303** [comment]
大佬，通过getNextData()获取到的录音数据如何转换成pcm的？

**Comment by julin69** [comment]
> 大佬，通过getNextData()获取到的录音数据如何转换成pcm的？

getNextData()取到的数据本身就是pcm的，后端直接保存成pcm文件就可以了，然后你可以播放生成的pcm文件试试

**Comment by 18310035303** [comment]
谢谢，这边已解决

**Comment by 18310035303** [comment]
我这边录音数据通过new Blob后，通过websocket发送，发送到服务端了，但是在前端的newtwork中查看发现发送的包都是0，这websocket发送二进制数据有什么限制吗，你那边又遇到这个问题吗？

**Comment by julin69** [comment]
> 我这边录音数据通过new Blob后，通过websocket发送，发送到服务端了，但是在前端的newtwork中查看发现发送的包都是0，这websocket发送二进制数据有什么限制吗，你那边又遇到这个问题吗？

我觉得不应该再network里面去看，我每次都是用console.log看，你可以用console打出来看看，里面应该是有数据的。
