### ISSUE TITLE
采样率怎么不支持8000呢

### ISSUE THREAD

**Issue by julin69** [2fps/recorder#43]

**Comment by julin69** [comment]
如果要想支持采样率8000，应该怎么做？

**Comment by 2fps** [comment]
输出采样率传入8000就行啦，new Recorder时传入就行了

**Comment by julin69** [comment]
我试了啊，用8000生成出来的就变成了48000的采样率了

**Comment by julin69** [comment]
采样率只要设置成8000，生成出来的就变成了48000的采样率，太奇怪了

**Comment by 2fps** [comment]
实在不好意思，代码里对输出的采样率做了限制。。。目前已经加入了8000，请使用最新的包试下。

**Comment by julin69** [comment]
我用的是0.5.6的版本，0.5.6的版本支持8000吗？因为我们需要支持边录边播

**Comment by 2fps** [comment]
使用 0.5.7 版本吧

**Comment by julin69** [comment]
好的，谢谢
