### ISSUE TITLE
为什么 getRecordAnalyseData返回的全是128

### ISSUE THREAD

**Issue by SuiFengErQu** [2fps/recorder#44]
start开始录音的时候，获取波形数据，数组里全是128，怎么根据声音高低来得到对的数据绘制出来
play的时候，getPlayAnalyseData返回的也全是128，显示的波形是一条横线

**Comment by 2fps** [comment]
底层用的是原声的`getByteTimeDomainData `方法，无波动就是128，请扩大观察范围，保证是在录音期间获取的值，并尝试提高音量试下。demo中的方案可以参考下。

**Comment by SuiFengErQu** [comment]
要在录音的时候实时获取的和绘制canvas吗，才能显示出波形动画？

**Comment by 2fps** [comment]
是的，getRecordAnalyseData获取的是实时的情况，需要在录音的时候实时绘制
