### ISSUE TITLE
火狐75.0版本还提示Error : 浏览器不支持 getUserMedia !，使用的是getPermission返回的错误

### ISSUE THREAD

**Issue by SuiFengErQu** [2fps/recorder#46]

**Comment by SuiFengErQu** [comment]
使用的是vuejs写的 手机浏览器，手机app上都不行，只有电脑网页可以, 麦克风权限应该怎么解决

**Comment by 2fps** [comment]
安卓的还是ios的？手机端的话，很多浏览器是不支持getUserMedia方法的，可以看下readme中，所以无法使用该库

**Comment by SuiFengErQu** [comment]
> 安卓的还是ios的？手机端的话，很多浏览器是不支持getUserMedia方法的，可以看下readme中，所以无法使用该库
我们吧手机浏览器端改成https就可以了

**Comment by SuiFengErQu** [comment]
> 安卓的还是ios的？手机端的话，很多浏览器是不支持getUserMedia方法的，可以看下readme中，所以无法使用该库

我们这把手机浏览器端加https就可以用了
