### ISSUE TITLE
使用边录边获取数据，切换到0.5.6版本后不能录音了

### ISSUE THREAD

**Issue by 18310035303** [2fps/recorder#47]

**Comment by 2fps** [comment]
有出现什么报错么？我这边尝试0.5.6是可以的啊？

**Comment by 18310035303** [comment]
这个跟vue版本有关吗，没有任何报错，获取到的音频文件大小为0

**Comment by 18310035303** [comment]
发现这个问题了，我在开始录音的回调函数里调动websocket，结束录音后没有录上，还有作者大大，我获取到数据后给后端发送字节流，怎么是0啊，我这边是通过websocket去发送的。

**Comment by smallcoders** [comment]
> 发现这个问题了，我在开始录音的回调函数里调动websocket，结束录音后没有录上，还有作者大大，我获取到数据后给后端发送字节流，怎么是0啊，我这边是通过websocket去发送的。

你好，使用getNextData()获取的dataView 怎么处理的
