### ISSUE TITLE
[Error]: Requested device not found

### ISSUE THREAD

**Issue by Bruce-zxy** [2fps/recorder#5]
![image](https://user-images.githubusercontent.com/22904758/59764592-af17c680-92ce-11e9-9980-33ddfc90c40b.png)

如图，用Chrome 70.0打开示例网页会报这个错误，小米5和小米MIX2用自带浏览器打开也无法录音

**Comment by 2fps** [comment]
1. 我这的chrome（70.0.3538.102） 是没问题的。出现这个报错的话，请去设备管理器中看下音频设备有没有被禁用或者坏了。
2. 移动端的话，还没有测试过，，如果可以的话，麻烦访问 [https://ie.icoa.cn/](https://ie.icoa.cn/) 提供下浏览器的内核版本。
3. getUserMedia接口增加对老api的兼容（新api只能支持到chrome 53版本，修改后理论上可以支持到21版本，自测39版本没问题）。

**Comment by Bruce-zxy** [comment]
PC上的UserAgent是：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
![image](https://user-images.githubusercontent.com/22904758/59860473-77357f80-93b1-11e9-8430-e026385974db.png)


小米自带的浏览器是：Mozilla/5.0 (Linux; U; Android 8.0.0; zh-cn; MIX 2 Build/OPR1.170623.027) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.8.1
![image](https://user-images.githubusercontent.com/22904758/59860517-9207f400-93b1-11e9-8f49-e1381156b467.png)


音频设备是没有坏的，我用Windows自带的麦克风设备测试过了

**Comment by 2fps** [comment]
拿同事的小米手机测试了，是不支持的。
移动端音频这块很尴尬，拿了最基本的video播放getusermedia流的demo，好几款国产浏览器都是有视频，却没有声音。

Requested device not found，还有可能就是音频设备被占用了，或者Chrome在检测音频设备时出现error了。

**Comment by xiangyuecn** [comment]
## 移动端
UC系列的浏览器几乎都不支持getUserMedia（表面提供了这个函数，但目测是个假的），包括但不限于：UC浏览器、支付宝、大部分国产rom自带浏览器。 

如果是腾讯X5内核的浏览器没有此问题：微信、QQ、部分采用X5的国产rom系统浏览器。

chrome、firefox、webview没有此问题。
