### ISSUE TITLE
录音文件大小问题

### ISSUE THREAD

**Issue by 18310035303** [2fps/recorder#56]
设置相同的采样率、通道、采样位数录制的音频文件大小与标准的音频计算方法计算的文件大小不一致
标准计算方法: 音频大小 = 采样率x声道数x采样位数字节数x时间
列：16000*1*2*0.02（毫秒）=640
而插件得出的是2730 
想问问怎么解决这个问题

**Comment by 2fps** [comment]
计算公式不是 **采样频率 × 采样位数 × 声道数 × 时间（秒）/ 8 = X（字节）** 么

插件中，如果输出采样率大于输入的采样率，最后实际输出的采样率还是输入采样率的大小，即只对音频有压缩没有扩大
