### ISSUE TITLE
如何自己修改插件

### ISSUE THREAD

**Issue by zhao421664959** [2fps/recorder#58]
npm -i 下载到项目后，由于自己的项目需要需要修改一下逻辑，怎么做呢，尝试把代码下载到本地后修改源码编译替换掉项目中的js-audio-recoder下面的dist后报错，怎么做

**Comment by 2fps** [comment]
你把项目clone到你本地啊，在`run start`启动本地的环境，在src文件夹下改完后，`run build`，把dist文件夹下的替换就行了
