### ISSUE TITLE
发布到服务器上的问题

### ISSUE THREAD

**Issue by wxm0019** [2fps/recorder#63]
我的是vue项目，在本地运行到谷歌浏览器上好好的，但是打包发布到服务器上，再通过域名访问就报错     Error : 浏览器不支持 getUserMedia !  又遇到过这个问题的吗，怎么解决啊

**Comment by 2fps** [comment]
同样版本的浏览器么？是不是没有上https？？

**Comment by fine-ypc** [comment]
这错误百度一下就知道答案了吧，没必要弄issue。
