### ISSUE TITLE
前后端分离项目，是否可以将实时的录音数据传递到后端去？

### ISSUE THREAD

**Issue by zihaoxin11** [2fps/recorder#69]
前端用的是angular，怎么获取实时的录音数据，同时将录音数据传递到后端去呢？

**Comment by qq2575896094** [comment]
+1

**Comment by 2fps** [comment]
可以的，和普通的请求没啥区别呀，不过传输的数据是二进制而已。

以前的[demo](https://github.com/2fps/demo/blob/master/view/2019/01/%E5%9F%BA%E4%BA%8E%E9%98%BF%E9%87%8C%E4%BA%91%E5%AE%9E%E7%8E%B0%E7%AE%80%E5%8D%95%E7%9A%84%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB%E5%8A%9F%E8%83%BD(node)/view/index.html) 可以参考下。

**Comment by qq2575896094** [comment]
使用getPCMBlob方法获取数据会暂停录音的

**Comment by zihaoxin11** [comment]
多谢多谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "涛走云散"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 上午10:49
收件人: "2fps/recorder"<recorder@noreply.github.com&gt;; 
抄送: "潇湘*夜雨"<553112052@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [2fps/recorder] 前后端分离项目，是否可以将实时的录音数据传递到后端去？ (#69)





 
可以的，和普通的请求没啥区别呀，不过传输的数据是二进制而已。
 
以前的demo 可以参考下。

**Comment by MuuuJian** [comment]
可以试试这个https://github.com/MuGuiLin/VoiceDictation
