### ISSUE TITLE
Recorder.getPermission() ios报：浏览器不支持getUserMedia

### ISSUE THREAD

**Issue by lvzhiming0808** [2fps/recorder#70]

**Comment by 2fps** [comment]
ios下就 safari的可以使用，chrome、firefox都是不支持该api的

**Comment by ParadiseWitch** [comment]
navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

**Comment by douwzy** [comment]
> navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
请问一下，你解决报错的问题了吗？
